### ISSUE TITLE
Multiple instances of SolarWinds when inputting "Pin" into the search box

### ISSUE THREAD

**Issue by DevBaddy** [2factorauth/frontend#50]
- [x] I have searched [open issues and pull requests](https://github.com/2factorauth/twofactorauth/issues?q=is%3Aopen). The issue I'm creating is not a duplicate of an existing open issue or pull request.

### Information about the bug: ###

**Bug description:**

Whenever you would input "Pin" into the search bar on 2fa.directory, there would be multiple instances of SolarWinds showing up.

![bug](https://user-images.githubusercontent.com/68301104/235325950-f8e5b6fb-0371-4460-8bc3-7fd7523bb2dc.png)

**Bug reproduction:**

Go to 2fa.directory -> Input "Pin" into the searchbox.

**Impacted devices:**

Desktop: Using a Windows 11 computer. This issue has been seen on Firefox, Edge and Chrome. Screen dimension: 5120x1440
iPhone: Tested this on Safari on a iPhone 13 Pro Max. iOS version: 16.4.1

**Expected behavior:**

1. SolarWinds shouldn't be popping up in the first place, as it doesn't contain "Pin"
2. If it was supposed to show up for some reason, there shouldn't be multiple instances of it.

**Additional information:**

No additional information.

**Comment by hkamran80** [comment]
It shows up multiple times because it is in [multiple categories](https://github.com/2factorauth/twofactorauth/blob/master/entries/s/solarwinds.com.json#L15-L19). As far as I know, that's expected. It shows up when you search for "pin" because one of its [additional domains](https://github.com/2factorauth/twofactorauth/blob/master/entries/s/solarwinds.com.json#L4-L10) is `pingdom.com`
